spring:
  application:
    name: spring-boot-kafka

  task: # Async Config
    execution:
      thread-name-prefix: "KafkaProducerThread-"
      pool:
        core-size: 1

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      topic: test
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0  # Acknowledgment level (0, 1, all/-1)
      retries: 3
      batch-size: 16384  # Batch size in bytes
      properties:
        linger.ms: 5
        delivery.timeout.ms: 300000
        allow.auto.create.topics: false

    consumer:
      topic: test
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.records: 500
        max.poll.interval.ms: 300000
        allow.auto.create.topics: false

    listener:   # Listener configuration
      concurrency: 3    # Concurrency level